services:
  app:
    image: bdemada/docker_workflows_test
    ports:
      - "8080:8080"
    watchtower:
      image: containrrr/watchtower
      environment:
        - WATCHTOWER_CLEANUP=true
        - WATCHTOWER_INCLUDE_STOPPED=true
        - WATCHTOWER_POLL_INTERVAL=120
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
    restart: unless-stopped